# Generated by Django 4.2.6 on 2023-11-02 12:13

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_lection_text_file_lection_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lection',
            name='file',
            field=models.FileField(blank=True, upload_to=catalog.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
    ]
