# Generated by Django 4.2.6 on 2023-11-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_takentest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
