# Generated by Django 4.2.6 on 2023-11-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_rename_group_mygroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('can_pass', 'Can pass test'),)},
        ),
    ]
